version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    depends_on: 
      - db
    build: ./backend/
    env_file: .env.example
    volumes:
      - static:/backend_static/
      - media:/media/
  frontend:
    env_file: .env.example
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    depends_on:
      - frontend
      - backend
    build: ./gateway/
    env_file: .env.example
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/media/