version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on: 
      - db
    image: mank000/kittygram_backend
    env_file: .env.example
    volumes:
      - static:/backend_static/
      - media:/media/
  frontend:
    env_file: .env.example
    image: mank000/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    depends_on:
      - frontend
      - backend
    image: mank000/kittygram_gateway
    env_file: .env.example
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/media/